#!/usr/bin/env bash

set -u
set -e

cd $HOME/obd
source secret.sh

sensor=$($HOME/obd/battery.py)
hass_friendly_name="sensorpi1 PiSugar3 battery level"
hass_name="sensorpi1_battery_percent"

curl -s -X POST -H "Authorization: Bearer $hass_llac" \
   -H "Content-Type: application/json" \
   -d "{\"state\": \"$sensor\", \"attributes\": {\"unit_of_measurement\": \"%\", \"friendly_name\": \"$hass_friendly_name\"}}" \
   https://hass.vanstaveren.us/api/states/sensor.$hass_name > /dev/null

sensor=$($HOME/obd/charging_status.py)
hass_friendly_name="sensorpi1 PiSugar3 charging status"
hass_name="sensorpi1_charging_status"

curl -s -X POST -H "Authorization: Bearer $hass_llac" \
   -H "Content-Type: application/json" \
   -d "{\"state\": \"$sensor\", \"attributes\": {\"friendly_name\": \"$hass_friendly_name\"}}" \
   https://hass.vanstaveren.us/api/states/sensor.$hass_name > /dev/null

sensor=$(/sbin/iwconfig wlan0 | grep ESSID | cut -d\" -f2)
hass_friendly_name="sensorpi1 PiSugar3 wifi name"
hass_name="sensorpi1_wifi_name"

curl -s -X POST -H "Authorization: Bearer $hass_llac" \
   -H "Content-Type: application/json" \
   -d "{\"state\": \"$sensor\", \"attributes\": {\"friendly_name\": \"$hass_friendly_name\"}}" \
   https://hass.vanstaveren.us/api/states/sensor.$hass_name > /dev/null

sensor="$(git log -1 --format=%cd) $(git rev-parse --short HEAD)"
hass_friendly_name="sensorpi1 git rev"
hass_name="sensorpi1_git_rev"

curl -s -X POST -H "Authorization: Bearer $hass_llac" \
   -H "Content-Type: application/json" \
   -d "{\"state\": \"$sensor\", \"attributes\": {\"friendly_name\": \"$hass_friendly_name\"}}" \
   https://hass.vanstaveren.us/api/states/sensor.$hass_name > /dev/null
