#!/usr/bin/env bash

cd $(dirname $(realpath $0))

changed=0

for unit in obd.service rtc-sync.service; do
    diff -u "$unit" "/etc/systemd/system/$unit" 2>/dev/null
    if [ $? -ne 0 ]; then
        echo "Installing $unit..."
        sudo cp -pv "$unit" /etc/systemd/system/
        changed=1
    fi
done

if [ $changed -eq 1 ]; then
    echo "Reloading systemd"
    sudo systemctl daemon-reload
fi

echo "Enabling systemd services"
# It seems normal for these to output an error, however they do succeed:
sudo systemctl enable obd
sudo systemctl enable rtc-sync
